### ISSUE TITLE
Опечатка в заголовке урока #sequence-comprehensions/1

### ISSUE THREAD

**Issue by sm00th1980** [clojurescript-ru/clojurescript.ru#1]
url: https://clojurescript.ru/koans/#sequence-comprehensions/1

Вижу заголовок: Выражение последовательности присваивает новое значение локальному симлову на каждой итерации

Должно быть: Выражение последовательности присваивает новое значение локальному символу на каждой итерации

**Comment by roman01la** [comment]
@sm00th1980 PR is welcome
